### ISSUE TITLE
Working of the dormancy policy

### ISSUE THREAD

**Issue by Reception123** [miraheze/CreateWiki#20]
Steps so that the dormancy policy works fully. @Southparkfan 
1.
- [x] Add something about the policy on RequestWiki 

 2 PRIORITY!
- [x] Make/Re-make a script to identify inactive wikis

3.

- [ ] Make a online-editable DB list (Special:ManageWiki)

**Comment by Reception123** [comment]
@Southparkfan We have to take care of 1 ASAP

**Comment by Reception123** [comment]
@Southparkfan Will probably work on 2 and 3 (2 is the priority)

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T136.
