### ISSUE TITLE
Parse error: syntax error, unexpected '[' in domain.com\extensions\CreateWiki-master\SpecialRequestWiki.php on line 52

### ISSUE THREAD

**Issue by Movyn** [miraheze/CreateWiki#21]
Hello,
I got this Error when iwant enter to Special pages after Install extension.

**Comment by Southparkfan** [comment]
@Movyn: sounds like an issue with PHP array dereferencing. It is a feature introduced in PHP 5.4, and thus anything below PHP 5.4 (e.g. 5.3, which is primarily used by Ubuntu 12.04 and Debian 6 servers) will give this error.

At Miraheze we run HHVM 3.9 which equals to PHP 5.6. I strive to maintain compatibility with PHP >= 5.4 (Debian 7 has 5.4, Ubuntu 14.04 has 5.5 and Debian 8 has 5.6).

Are you able to upgrade to PHP 5.4?

**Comment by Movyn** [comment]
Hello there,
Thanks for that. Yes i try to upgrade and error is now solved.

Currently New problem is after creation new wiki, in Special:RequestWiki Page, i got this error:

Database error

A database query error has occurred. This may indicate a bug in the software.

What is that and how can i solve this one?

**Comment by Southparkfan** [comment]
https://www.mediawiki.org/wiki/Manual:How_to_debug#SQL_errors

You likely need to import the cw_wikis.sql file into your database.

Also, this extension is very Miraheze specific. A wildcard A(AAA) needs to point to your server, you need to run the DBListGenerator.php script and you need to copy almost our whole LocalSettings.php to make it work.

**Comment by Movyn** [comment]
Thanks. After enable SQL error, i found problem. actually DB needed on two cw_request and cw_wikis.sql because doesn't exist on DB library. I use prefix_ for standard tables, maybe this caused our problem.

This time I start Create new wiki and with successful. now in queue i can see this new wiki as status: in review, how can i activate it?

**Comment by Southparkfan** [comment]
You need the 'createwiki' right.

**Comment by Movyn** [comment]
How can i have it? i can't find about.

**Comment by Southparkfan** [comment]
$wgGroupPermissions['sysop']['createwiki'] = true;

**Comment by Movyn** [comment]
Thanks. 
For Database name, if i use my default Database name i got this error:
A wiki with that database name already exists.

If i use new DB name i got this one
The database name doesn't end in a valid suffix (e.g. 'wiki').

and if i create new DB on CPanel and use that name i got again this one:
A wiki with that database name already exists.

**Comment by Southparkfan** [comment]
Do you have $wgConf = new SiteConfiguration; $wgConf->suffixes = array('wiki'); set?

**Comment by Movyn** [comment]
i don't think so. in LocalSettings.php i don't see that.

**Comment by Movyn** [comment]
well, i add this two line on localsetting. i can't ise DB name with underline (like db_name). after use for example clashwiki as DB name, i got error:
    Query:
    CREATE DATABASE `clashwiki`;
    Function: DatabaseBase::query
    Error: 1044 Access denied for user 'user'@'localhost' to database 'clashwiki' (localhost)

Notice: JobQueueGroup::__destruct: 1 buffered job(s) of type(s) RecentChangesUpdateJob never inserted. in /home/bazipedi/public_html/miuwik/includes/jobqueue/JobQueueGroup.php on line 420

**Comment by Southparkfan** [comment]
That is because the MySQL user of your wiki doesn't have the appropriate privileges.

Looking at your file path, it looks like you are using shared hosting. Shared hosting won't allow you to create databases without a prefix (i.e. only u39045879_clashwiki can be created).

**Comment by Movyn** [comment]
Yes this is shared hosting. But MySQL user have full access on main Database.
Also Yes, Database most be something like that: originaldb_{newwikidbname}.
So there is no way to use this extension? if extension allow DB name created on hosting (error: A wiki with that database name already exists.) or if we can use underline maybe it work.

**Comment by Movyn** [comment]
So there is no solution for shared hosting?

**Comment by Southparkfan** [comment]
Actually not.

You really need a server with root access.

**Comment by Movyn** [comment]
Thank you, Southparkfan. have a good year.

**Comment by Southparkfan** [comment]
Same to you.

And you are always welcome to get a wiki at Miraheze :-)
