### ISSUE TITLE
Make a way so that DB's with hyphens can't be submitted

### ISSUE THREAD

**Issue by Reception123** [miraheze/CreateWiki#24]
As A LOT of users are putting hyphens in their DB's we have to make a way to not let them submit their request, or find a way to allow hyphens in Miraheze CNAME's (which I don't think is possible)

**Comment by Reception123** [comment]
#25

**Comment by JohnFLewis** [comment]
Hyphens are perfectly legit on a DNS scale.

**Comment by Southparkfan** [comment]
But we don't allow them in dbnames currently. Not DNS related at all.

**Comment by JohnFLewis** [comment]
The issue however was worded as we need to prevent them be becauses it not possibles with regards to DNS. As such I closed it as the original issue was a non-issue.

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T153.
