### ISSUE TITLE
Add a special page that allows bureaucrats to manage some wiki settings

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/CreateWiki#27]
This was one of the first ideas before Miraheze even got its name.

* It should be called Special:ManageWiki, obviously
* This special page will be available on the wikis themselves, and usage should be logged
* We'll decommission deleted.dblist, closed.dblist and private.dblist.
* The cw_wikis table should be adjusted as needed
* /srv/mediawiki/dblist/all.dblist will contain JSON that looks like this:
```
{
   "metawiki": {
      "extensions": [
         "Extension1",
         "Extension2"
      ],
      "settings": {
         "logo": "urltologo",
         "favicon": "urltofavicon"
      },
      "private": false,
      "closed": false
   },
   "southparkfanwiki": {
      "extensions": [
         "Extension1",
         "Extension2"
      ],
      "settings": {
         "logo": "urltologo",
         "favicon": "urltofavicon"
      },
      "private": true,
      "closed": false
   }
}
```

Miraheze will never be the same anymore.

**Comment by Reception123** [comment]
@Southparkfan So is ManageWiki going to be completed then?

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T194.
