### ISSUE TITLE
Do not use GitHub issues for reporting issues!

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/CreateWiki#28]
As of April 2016, we migrated from GitHub's issue tracking to Phabricator. If you want to file an issue, please visit https://phabricator.miraheze.org. You can register and login with your GitHub account.

**Comment by LegoFan4000** [comment]
Why not go into the settings tab and disable issues alltogether? @Southparkfan @JohnFLewis @NDKilla @NDKilla-public

**Comment by Reception123** [comment]
@LegoFan4000 Please do not ping users for non-important and/or urgent things. It has been done like this so that users can actually know where to report issues and not just see that there is no issue tab.
