### ISSUE TITLE
Rights&mainpage

### ISSUE THREAD

**Issue by Reception123** [miraheze/CreateWiki#5]
- [ ] Fix automatically granting rights
- [ ] Fix mainpage automatic creation

**Comment by Southparkfan** [comment]
Each problem should get their own issue. Also - rights are automatically granted?

**Comment by Reception123** [comment]
They should be, but when I use createwiki it gives me an error

**Comment by addshore** [comment]
What is the error?
This is perhaps why I added lazy errors in places

**Comment by Southparkfan** [comment]
The if check for the output of the promoteAccount script always fails and gives an error, even while rights are granted?
