### ISSUE TITLE
Creation of user account fails

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/CreateWiki#6]
Mon Aug 24 12:58:56 UTC 2015    mw1     delete3wiki     User::addToDatabase    185.52.1.77      1205    Lock wait timeout exceeded; try restarting transaction (185.52.1.77)    INSERT IGNORE INTO `user` (user_id,user_name,user_password,user_newpassword,user_newpass_time,user_email,user_email_authenticated,user_real_name,user_token,user_registration,user_editcount,user_touched) VALUES (NULL,'John','','',NULL,'',NULL,'','NULL','20150824125805','0','20150824125810')

(some data retracted for privacy)

**Comment by Southparkfan** [comment]
https://phabricator.wikimedia.org/T110034

**Comment by JohnFLewis** [comment]
Resolved thanks to some help from @jynus in https://github.com/miraheze/puppet/commit/5d39b8d013a5d088000da59e0e459987f1540008.
