### ISSUE TITLE
Configure editing wiki info/closing

### ISSUE THREAD

**Issue by Reception123** [miraheze/CreateWiki#7]
As users sometimes make a mistake and/or want a change to their wiki info (name, private, language) I think that instead of making it editable only through Shell that it should be editable some other way (like through a DB list that can be accessed easily by wiki creators).

**Comment by Reception123** [comment]
@Southparkfan

**Comment by Southparkfan** [comment]
I'm going to drop all work until Miraheze/mw-config#75 is fixed.

**Comment by Reception123** [comment]
Okay

**Comment by Reception123** [comment]
I think that per John, this is really important if we even want to think about implementing the dormancy policy. I would be happy to help.

**Comment by Reception123** [comment]
John on IRC "Also I don't think it should a manual check at all. A script should run on a cron and email a list of wikis to close/delete. That way it will always be checked regularly and require no manual work"

**Comment by Reception123** [comment]
Not needed anymore, in #20
