### ISSUE TITLE
Convert special pages to use OOUI

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/CreateWiki#8]
A big campaign (https://phabricator.wikimedia.org/T100270) is ongoing to use OOUI special pages, and as I like at least some of the OOUI stuff (and there are already multiple MediaWiki core special pages using OOUI), I think CreateWiki should use it too.

**Comment by Southparkfan** [comment]
Special:CreateWiki has been converted a while ago.

**Comment by NDKilla** [comment]
@Southparkfan Per your previous comment, closeing this?

**Comment by Southparkfan** [comment]
Actually, it's not done yet :)

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T46.
